import iconMapping from "./iconMapping.json";
import { CryptoMeta } from "../components/types/types";

export const CRYPTO_META: CryptoMeta[] = [
  {
    prefix: "BTC",
    name: "Bitcoin",
    iconUrl: iconMapping["BTC"],
    color: "text-orange-500",
  },
  {
    prefix: "ETH",
    name: "Ethereum",
    iconUrl: iconMapping["ETH"],
    color: "text-blue-400",
  },
  {
    prefix: "SOL",
    name: "Solana",
    iconUrl: iconMapping["SOL"],
    color: "text-green-400",
  },
  {
    prefix: "ADA",
    name: "Cardano",
    iconUrl: iconMapping["ADA"],
    color: "text-blue-500",
  },
  {
    prefix: "DOT",
    name: "Polkadot",
    iconUrl: iconMapping["DOT"],
    color: "text-pink-500",
  },
  {
    prefix: "MATIC",
    name: "Polygon",
    iconUrl: iconMapping["MATIC"],
    color: "text-purple-500",
  },
  {
    prefix: "DOGE",
    name: "Dogecoin",
    iconUrl: iconMapping["DOGE"],
    color: "text-yellow-500",
  },
  {
    prefix: "ETC",
    name: "Ethereum Classic",
    iconUrl: iconMapping["ETC"],
    color: "text-green-600",
  },
  {
    prefix: "HBAR",
    name: "Hedera",
    iconUrl: iconMapping["HBAR"],
    color: "text-green-500",
  },
  {
    prefix: "MKR",
    name: "Maker",
    iconUrl: iconMapping["MKR"],
    color: "text-teal-500",
  },
  {
    prefix: "KNC",
    name: "Kyber Network",
    iconUrl: iconMapping["KNC"],
    color: "text-cyan-500",
  },
  {
    prefix: "ZRX",
    name: "0x",
    iconUrl: iconMapping["ZRX"],
    color: "text-gray-500",
  },
  {
    prefix: "CHR",
    name: "Chromia",
    iconUrl: iconMapping["CHR"],
    color: "text-blue-400",
  },
  {
    prefix: "ANKR",
    name: "Ankr",
    iconUrl: iconMapping["ANKR"],
    color: "text-blue-500",
  },
  {
    prefix: "1INCH",
    name: "1inch",
    iconUrl: iconMapping["1INCH"],
    color: "text-gray-700",
  },
  {
    prefix: "STORJ",
    name: "Storj",
    iconUrl: iconMapping["STORJ"],
    color: "text-blue-400",
  },
  {
    prefix: "BAT",
    name: "Basic Attention Token",
    iconUrl: iconMapping["BAT"],
    color: "text-orange-600",
  },
  {
    prefix: "SUSHI",
    name: "SushiSwap",
    iconUrl: iconMapping["SUSHI"],
    color: "text-blue-600",
  },
  {
    prefix: "BCH",
    name: "Bitcoin Cash",
    iconUrl: iconMapping["BCH"],
    color: "text-green-500",
  },
  {
    prefix: "EOS",
    name: "EOS",
    iconUrl: iconMapping["EOS"],
    color: "text-black",
  },
  {
    prefix: "XLM",
    name: "Stellar",
    iconUrl: iconMapping["XLM"],
    color: "text-gray-400",
  },
  {
    prefix: "CELO",
    name: "Celo",
    iconUrl: iconMapping["CELO"],
    color: "text-yellow-500",
  },
  {
    prefix: "MASK",
    name: "Mask Network",
    iconUrl: iconMapping["MASK"],
    color: "text-purple-500",
  },
  {
    prefix: "DYDX",
    name: "dYdX",
    iconUrl: iconMapping["DYDX"],
    color: "text-purple-600",
  },
  {
    prefix: "GALA",
    name: "Gala",
    iconUrl: iconMapping["GALA"],
    color: "text-yellow-600",
  },
  {
    prefix: "SKL",
    name: "SKALE",
    iconUrl: iconMapping["SKL"],
    color: "text-blue-500",
  },
  {
    prefix: "REN",
    name: "Ren",
    iconUrl: iconMapping["REN"],
    color: "text-gray-600",
  },
  {
    prefix: "GRT",
    name: "The Graph",
    iconUrl: iconMapping["GRT"],
    color: "text-purple-500",
  },
  {
    prefix: "BAL",
    name: "Balancer",
    iconUrl: iconMapping["BAL"],
    color: "text-purple-400",
  },
  {
    prefix: "COMP",
    name: "Compound",
    iconUrl: iconMapping["COMP"],
    color: "text-green-600",
  },
  {
    prefix: "UMA",
    name: "UMA",
    iconUrl: iconMapping["UMA"],
    color: "text-red-500",
  },
  {
    prefix: "YFI",
    name: "Yearn.finance",
    iconUrl: iconMapping["YFI"],
    color: "text-blue-700",
  },
  {
    prefix: "ENJ",
    name: "Enjin Coin",
    iconUrl: iconMapping["ENJ"],
    color: "text-purple-500",
  },
  {
    prefix: "CHZ",
    name: "Chiliz",
    iconUrl: iconMapping["CHZ"],
    color: "text-red-600",
  },
  {
    prefix: "CRV",
    name: "Curve DAO",
    iconUrl: iconMapping["CRV"],
    color: "text-blue-500",
  },
  {
    prefix: "RNDR",
    name: "Render Token",
    iconUrl: iconMapping["RNDR"],
    color: "text-purple-600",
  },
  {
    prefix: "APE",
    name: "ApeCoin",
    iconUrl: iconMapping["APE"],
    color: "text-blue-500",
  },
  {
    prefix: "ENS",
    name: "Ethereum Name Service",
    iconUrl: iconMapping["ENS"],
    color: "text-blue-400",
  },
  {
    prefix: "FTM",
    name: "Fantom",
    iconUrl: iconMapping["FTM"],
    color: "text-blue-500",
  },
  {
    prefix: "MANA",
    name: "Decentraland",
    iconUrl: iconMapping["MANA"],
    color: "text-red-500",
  },
  {
    prefix: "SAND",
    name: "The Sandbox",
    iconUrl: iconMapping["SAND"],
    color: "text-blue-400",
  },
  {
    prefix: "USDC",
    name: "USD Coin",
    iconUrl: iconMapping["USDC"],
    color: "text-blue-500",
  },
  {
    prefix: "XTZ",
    name: "Tezos",
    iconUrl: iconMapping["XTZ"],
    color: "text-blue-600",
  },
  {
    prefix: "XMR",
    name: "Monero",
    iconUrl: iconMapping["XMR"],
    color: "text-orange-500",
  },
  {
    prefix: "QNT",
    name: "Quant",
    iconUrl: iconMapping["QNT"],
    color: "text-red-500",
  },
  {
    prefix: "SHIB",
    name: "Shiba Inu",
    iconUrl: iconMapping["SHIB"],
    color: "text-orange-600",
  },
  {
    prefix: "CTSI",
    name: "Cartesi",
    iconUrl: iconMapping["CTSI"],
    color: "text-blue-500",
  },
  {
    prefix: "SNX",
    name: "Synthetix",
    iconUrl: iconMapping["SNX"],
    color: "text-blue-400",
  },
  {
    prefix: "LRC",
    name: "Loopring",
    iconUrl: iconMapping["LRC"],
    color: "text-blue-500",
  },
  {
    prefix: "AXS",
    name: "Axie Infinity",
    iconUrl: iconMapping["AXS"],
    color: "text-blue-600",
  },
  {
    prefix: "USDT",
    name: "Tether",
    iconUrl: iconMapping["USDT"],
    color: "text-green-500",
  },
  {
    prefix: "BAND",
    name: "Band Protocol",
    iconUrl: iconMapping["BAND"],
    color: "text-blue-500",
  },
  {
    prefix: "OMG",
    name: "OMG Network",
    iconUrl: iconMapping["OMG"],
    color: "text-blue-400",
  },
  {
    prefix: "SUPER",
    name: "SuperFarm",
    iconUrl: iconMapping["SUPER"],
    color: "text-purple-500",
  },
  {
    prefix: "ETHW",
    name: "EthereumPoW",
    iconUrl: iconMapping["ETHW"],
    color: "text-gray-500",
  },
  {
    prefix: "DASH",
    name: "Dash",
    iconUrl: iconMapping["DASH"],
    color: "text-blue-500",
  },
  {
    prefix: "EGLD",
    name: "MultiversX",
    iconUrl: iconMapping["EGLD"],
    color: "text-purple-600",
  },
  {
    prefix: "DAI",
    name: "Dai",
    iconUrl: iconMapping["DAI"],
    color: "text-yellow-400",
  },
  {
    prefix: "PAXG",
    name: "PAX Gold",
    iconUrl: iconMapping["PAXG"],
    color: "text-yellow-500",
  },
  {
    prefix: "UST",
    name: "TerraClassicUSD",
    iconUrl: iconMapping["UST"],
    color: "text-blue-500",
  },
  {
    prefix: "ALICE",
    name: "My Neighbor Alice",
    iconUrl: iconMapping["ALICE"],
    color: "text-pink-500",
  },
];

export const WEBSOCKET_URL =
  "wss://newton-websocket-server-f3fc73957856.herokuapp.com/markets/ws";
